# Generated by Django 5.0.1 on 2024-01-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('DEPTNO', models.IntegerField(primary_key=True, serialize=False)),
                ('DNAME', models.CharField(max_length=255)),
                ('LOC', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('GRADE', models.IntegerField(primary_key=True, serialize=False)),
                ('LOSAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HISAL', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EMPNO', models.IntegerField(primary_key=True, serialize=False)),
                ('ENAME', models.CharField(max_length=255)),
                ('JOB', models.CharField(max_length=255)),
                ('HIREDATE', models.DateField()),
                ('SAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COMM', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DEPTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('MGR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
